### PR TITLE
Add screenshot of unfocused old comment box

### PR DESCRIPTION
**Pull request by siddharthkp**
Noticed, you said you couldn't find an unfocused one, so I took a screenshot from a staging server.

Completely optional of course! Only if it makes sense to you in the flow of the article

### CODE REVIEW

**Review by LeaVerou — CHANGES_REQUESTED** [review]
Hey, thanks so much for that!

Small tweaks:
- Can you use two images in the same figure, like I did with the screenshots of the fixed comment area?
- Can you take two screenshots, one focused and one unfocused, so that they're the same?

Are you 100% sure this is the most commonly deployed version previously? I'd swear there was a border around the "Attach files…" area.

**Comment by siddharthkp** [comment]
> Are you 100% sure this is the most commonly deployed version previously? I'd swear there was a border around the "Attach files…" area.

It does look really off without the order 🤔 Let me double check!

**Comment by siddharthkp** [comment]
> Small tweaks:
> Can you use two images in the same figure, like I did with the screenshots of the fixed comment area?
Done!

> Can you take two screenshots, one focused and one unfocused, so that they're the same?
Done

> Are you 100% sure this is the most commonly deployed version previously? I'd swear there was a border around the "Attach files…" area.

I checked, there was no border without focus!

**Review by LeaVerou — APPROVED** [review]

**Comment by LeaVerou** [comment]
Merged, thanks again!

**Pull request merged**
